<div id="modalWrapper"></div>

<?php
	
	$veiculoModal = DAOFactory::getVeiculoDAO()->relTable('
	
														SELECT 
														*,v.alias as alias,
														v.idAlbum as idAlbum,
														c.nome as idCor,
														vc.alias as idVeiculoCategoria,
														m.nome as idMarca,
														m.idMarca as km,
														fuel.tipo as idCombustivel,
														trans.tipo as idTransmissao,
														sen.tipo as idSensor
														
														FROM Veiculo v 
														
														INNER JOIN Marca m ON (v.idMarca=m.idMarca)
														INNER JOIN Cor c ON (c.idCor=v.idCor)
														LEFT JOIN Combustivel fuel ON (v.idCombustivel=fuel.idCombustivel)
														LEFT JOIN Transmissao trans ON (v.idTransmissao=trans.idTransmissao)
														lEFT JOIN Sensor sen ON (v.idSensor=sen.idSensor)
														INNER JOIN veiculoCategoria vc ON (vc.idVeiculoCategoria=v.idVeiculoCategoria)


														WHERE v.status>0  ');
													
for($i=0;$i<count($veiculoModal);$i++){ 
	
	$rowVeiculo = $veiculoModal[$i]; 
	$albumModal = DAOFactory::getAlbumMidiaDAO()->queryCondList(' idAlbum="'.$rowVeiculo->idAlbum.'" ORDER BY ordem ASC '); 										


?>
<div class="modal fade lux-modal" tabindex="-1" role="dialog" id="carro<?=$rowVeiculo->idVeiculo?>">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			
			<img src="assets/img/logo.png" alt="Lux Sell Ect" class="lux-modal__logo">

			<button class="lux-modal__close js-close" data-dismiss="modal" aria-label="Close">
				<span></span>
			</button>

			<div class="lux-modal-content">
				<div class="lux-modal__column">
					<div class="lux-modal-slider js-slider-modal">
						<?php for($j=0;$j<count($albumModal);$j++){  ?>
						<div data-fancybox="gallery<?= $i; ?>" href="/assets/img/albuns/album_<?=$albumModal[$j]->idAlbum?>/<?=$albumModal[$j]->file?>" class="lux-modal-slider__item" style="background-image: url(/assets/img/albuns/album_<?=$albumModal[$j]->idAlbum?>/<?=$albumModal[$j]->file?>); "></div>
						<?php } ?>
					</div>
					<div class="lux-modal-slider-nav js-slider-modal-nav">
						<?php for($j=0;$j<count($albumModal);$j++){  ?>
						<div class="lux-modal-slider-nav__item" style="background-image: url(/assets/img/albuns/album_<?=$albumModal[$j]->idAlbum?>/<?=$albumModal[$j]->file?>); "></div>
						<?php } ?>
					</div>
					<footer class="lux-modal__footer">
						<span>COMPARTILHAR: </span>
						<ul>
							<li><a href="https://www.facebook.com/sharer/sharer.php?u=<?=$siteUrl?>" target="_blank"><img src="assets/img/icons/facebook2.svg" alt="Facebook"></a></li>
							<li><a href="https://twitter.com/home?status=<?=$rowVeiculo->modelo?>%20@%20LuxSellEct%0A<?=$siteUrl?>" target="_blank"><img src="assets/img/icons/twitter2.svg" alt="Twitter"></a></li>
							<li><a href="mailto:?subject=Lux Sell Ect / <?=$rowVeiculo->modelo?>&body=%0A%0A<?=$rowVeiculo->idMarca?> - <?=$rowVeiculo->modelo?>%0A%0A<?=$siteTitle?>%0A<?=$siteUrl?>%0A%0A" target="_blank"><img src="assets/img/icons/email.svg" alt="Email"></a></li>
						</ul>
					</footer>
				</div>
				<div class="lux-modal__column">
					<div class="lux-modal__desc">
						<div class="lux-modal__title">
							<h4>
								<small><?=$rowVeiculo->idMarca?></small> <?=$rowVeiculo->modelo?>
							</h4>
						</div>

						<p><?=$rowVeiculo->motor?></p>
						<p><?=$rowVeiculo->km?></p>

						<div class="Car-info">
							<div class="Car-info__date">
								<?=$rowVeiculo->anoModelo?>
							</div>

							<div class="Car-info__price">
								<?=$rowVeiculo->preco?>
							</div>
						</div>

						<div class="js-scrollbar">
						
						<ul>	
							<?php if($rowVeiculo->idMarca!=''){ ?><li><strong>Marque:</strong> <span><?=$rowVeiculo->idMarca?></span></li><?php } ?>  
							<?php if($rowVeiculo->modelo!=''){ ?><li><strong>Modèle:</strong> <span><?=$rowVeiculo->modelo?></span></li><?php } ?>  
							<?php if($rowVeiculo->preco!=''){ ?><li><strong>Prix:</strong> <span>R$ <?=$rowVeiculo->preco?></span></li><?php } ?> 
							<?php if($rowVeiculo->idCor!=''){ ?><li><strong>Couleur:</strong> <span><?=$rowVeiculo->idCor?></span></li><?php } ?>
							<?php if($rowVeiculo->anoFabricacao!=''){ ?><li><strong>Année de fabrication:</strong> <span><?=$rowVeiculo->anoFabricacao?></span></li><?php } ?>
							<?php if($rowVeiculo->anoModelo!=''){ ?><li><strong>Année du modèle:</strong> <span><?=$rowVeiculo->anoModelo?></span></li><?php } ?>
							<?php if($rowVeiculo->km!=''){ ?><li><strong>Km:</strong> <span><?=$rowVeiculo->km?></span></li><?php } ?>  		
							<?php if($rowVeiculo->motor!=''){ ?><li><strong>Mteur:</strong> <span><?=$rowVeiculo->motor?></span></li><?php } ?>
							<?php if($rowVeiculo->potencia!=''){ ?><li><strong>Puissance:</strong> <span><?=$rowVeiculo->potencia?></span></li><?php } ?>
							<?php if($rowVeiculo->aceleracao!=''){ ?><li><strong>Accélération:</strong> <span><?=$rowVeiculo->aceleracao?></span></li><?php } ?>
							<?php if($rowVeiculo->airbag!=''){ ?><li><strong>Airbag:</strong> <span><?=$rowVeiculo->airbag?></span></li><?php } ?>
							<?php if($rowVeiculo->garantiaFabrica!=''){ ?><li><strong>Garantie Legale:</strong> <span><?=$rowVeiculo->garantiaFabrica?></span></li><?php } ?>
							<?php if($rowVeiculo->idCombustivel!=''){ ?><li><strong>Combustible:</strong> <span><?=$rowVeiculo->idCombustivel?></span></li><?php } ?>
							<?php if($rowVeiculo->idTransmissao!=''){ ?><li><strong>Transmission:</strong> <span><?=$rowVeiculo->idTransmissao?></span></li><?php } ?>
							<?php if($rowVeiculo->placa!=''){ ?><li><strong>Plaque:</strong> <span>XXX-<?=substr($rowVeiculo->placa, -4)?></span></li><?php } ?>
							<?php if($rowVeiculo->Portas!=''){ ?><li><strong>Les portes:</strong> <span><?=$rowVeiculo->portas?></span></li><?php } ?>
							<?php if($rowVeiculo->multimidia!=''){ ?><li><strong>Multimídia:</strong> <span><?=$rowVeiculo->multimidia?></span></li><?php } ?>
							<?php if($rowVeiculo->bancos!=''){ ?><li><strong>Sièges:</strong> <span><?=$rowVeiculo->bancos?></span></li><?php } ?>
							<?php if($rowVeiculo->freios!=''){ ?><li><strong>Freinage ABS:</strong> <span><?=$rowVeiculo->freios?></span></li><?php } ?>
							<?php if($rowVeiculo->farois!=''){ ?><li><strong>Phares:</strong> <span><?=$rowVeiculo->farois?></span></li><?php } ?>
							<?php if($rowVeiculo->rodas!=''){ ?><li><strong>Roues:</strong> <span><?=$rowVeiculo->rodas?></span></li><?php } ?>
							<?php if($rowVeiculo->idSensor!=''){ ?><li><strong>Capteurs de stationnement:</strong> <span><?=$rowVeiculo->idSensor?></span></li><?php } ?>
							<?php if($rowVeiculo->bluetooth=='sim'){ ?><li><strong>Bluetooth:</strong> <span><?=strtoupper($rowVeiculo->bluetooth)?></span></li><?php } ?>
							<?php if($rowVeiculo->tetoSolar=='sim' or $rowVeiculo->tetoSolar=='semipanoramico'){ ?><li><strtong>Plafond solaire:</strtong> <span><?=strtoupper($rowVeiculo->tetoSolar)?></span></li><?php } ?>
							<?php if($rowVeiculo->conversivel=='sim'){ ?><li><strong>Convertible:</strong> <span><?=($rowVeiculo->conversivel)?></span></li><?php } ?>
							
							<?php if($rowVeiculo->pilotoAutomatico=='sim'){ ?><li><strong>Pilote automatique:</strong> <span><?=strtoupper($rowVeiculo->pilotoAutomatico)?></span></li><?php } ?>
							
							<?php if($rowVeiculo->sensorChuva=='sim'){ ?><li><strong>Détecteur de pluie:</strong> <span><?=strtoupper($rowVeiculo->sensorChuva)?></span></li><?php } ?>
							<?php if($rowVeiculo->blindado=='sim'){ ?><li><strong>Blindado:</strong> <span><?=strtoupper($rowVeiculo->blindado)?></span></li><?php } ?>
							<?php if($rowVeiculo->observacoes!=''){ ?><li><br><br><strong>Observations:</strong> <span><?=strtoupper($rowVeiculo->observacoes)?></span></li><?php } ?>

						</ul>	
							
							
						</div>

						<a href="#Contact" class="Button js-scroll" data-dismiss="modal" aria-label="Close">
							Faire une proposition
						</a>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
<?php } ?>

 
	<div class="PageWrapper">
		<header class="Header">
			<div class="container">
				<a href="index.html" class="Header__logo">
					<img src="assets/img/logo.png" alt="Lux Sell Ect">
				</a>

				<span></span>

				<a href="#/" class="MenuTrigger">
					<span></span>
				</a>

				<nav class="Menu">
					<div class="Menu__info">
						<img src="assets/img/logo-negativo.png" alt="Lux Sell Ect">
						<p>
							Olá, <br><br> Bem vindo a página da Lux Sell Ect Automóveis.<br>Encontre os melhores veículos aqui.
						</p>

						<ul class="Menu__redes">
							<li>
								<a href="/#" target="_blank">
									<img src="assets/img/icons/facebook.svg" alt="Facebook">
								</a>
							</li>
							<li>
								<a href="/#" target="_blank">
									<img src="assets/img/icons/twitter.svg" alt="Twitter">
								</a>
							</li>
						</ul>
					</div> <!-- Menu__info -->

					<ul class="Menu__nav">
						<li><a href="#LuxSellEct" class="js-scroll">Société</a></li>
						<li><a href="#Releases" class="js-scroll">Cars</a></li>
						<li><a href="#index.html" class="Menu__navLogo"><img src="assets/img/logo.png" alt="Lux Sell Ect"></a></li>
						<li><a href="blog.html" target="_blank">BLOG</a></li>
						<li><a href="#Contact" class="js-scroll">CONTACT</a></li>
					</ul>
				</nav> <!-- Menu -->

			</div> <!-- container -->
		</header> <!-- Header -->

		<div class="PageContent">

			<section class="Banner js-bannerSlider">
				
				<?php 	
						$albumBannerHome = DAOFactory::getAlbumMidiaDAO()->queryCondList(' idAlbum="18" ORDER BY ordem ASC ');
						for($b=0;$b<count($albumBannerHome);$b++){ 
				  ?>
				
				<div class="Banner__item" style="background-image: url(/assets/img/albuns/album_<?=$albumBannerHome[$b]->idAlbum?>/<?=$albumBannerHome[$b]->file?>);">
					<div class="container">
						<div class="Banner__content">
							<h2><span><?=$albumBannerHome[$b]->nome?></span><?=$albumBannerHome[$b]->alt?></h2>
						</div> <!-- Banner-content -->
						<a href="#Releases" class="Banner__link js-scroll">NOUVELLES VERSIONS</a>
					</div> <!-- container -->
				</div>  <!-- Banner__item -->
				
				<?php } ?>
				
			</section> <!-- Banner -->

			<section id="Releases" class="Release">
				<div class="Release__title">
					<div class="container">
						<h3>NOUVELLES VERSIONS</h3>
					</div>
				</div>

				<div id="Cars" class="Grid js-grid">

					<!--<div class="Grid__item mix" data-marca="lamborghini" data-modelo="2013" data-valor="1000000">
						<div class="Grid__img" style="background-image: url(assets/img/carros/c1.jpg);"></div>
						
						<div class="Grid__content">
							<h4>
								<small>PORSCHE</small> PORSCHE 913
							</h4>

							<div class="Car-info">
								<div class="Car-info__date">
									2013
								</div>

								<div class="Car-info__price">
									700.000
								</div>
							</div>

						</div>
					</div>-->

			</div> <!-- js-grid -->

			<div class="Grid__load">
				<div class="container"></div>
			</div>


			</section> <!-- Release -->

			<section id="LuxSellEct" class="Info--border">
				<div class="Info__item">
					<div class="Info__img" style="background-image: url(assets/img/sobre.jpg);"></div>
					<div class="Info__text">
						<h3>Société</h3>
						<p>
							LuxSELLect, spécialiste "véhicules de sport et de prestige" depuis plus de 10 ans,
Notre spécialité : l’achat et la vente de véhicules de haut de gamme. Nous disposons d’un large choix grâce à notre propre stock et grâce aux véhicules que nos clients nous confient en dépôt vente.
						</p>
						<p>
Nous disposons d’une équipe spécialisée dans la recherche personnalisée afin de vous trouver un véhicule répondant parfaitement à vos critères les plus précis grâce à notre réseau européen de partenaires.
						</p>
					</div>
				</div>

				<div class="Info__item--right">
					<div class="Info__img" style="background-image: url(assets/img/sobre2.jpg);"></div>
					<div class="Info__text">
						<h3>QUALITÉ <br>GARANTIE</h3>
						<p>
							Depuis 2003, LuxSELLect se spécialise dans la vente de véhicules de luxe et de collection sur le marché de l'automobile en tant que synonyme de transparence, de fiabilité et de qualité. Nos véhicules sont vérifiés et certifiés, et notre inventaire est constamment rénové avec ce que il y a de le plus récent et plus exclusif. Ici vous trouverez la voiture que vous voulez.
						</p>
					</div>
				</div>
			</section> <!-- Info -->

			<section class="Instagram">
				<h3>
					SUIVEZ-NOUS <br>SUR INSTAGRAM
				</h3>

				<div class="container">

					<img src="assets/img/iphone.jpg" alt="Iphone" class="Instagram__iphone">

					<div class="Instagram__box">
						<img src="assets/img/logo-negativo.png" alt="Lux Sell Ect">
						<img src="assets/img/instagram.jpg" alt="Instagram">
						<div id="instafeed" class="Instafeed"></div>

					</div>
				</div>
			</section> <!-- Instagram -->

			<section class="Contato">
				<div class="Contato__column" style="background-image: url(assets/img/contato.jpg); "></div>
				<div class="Contato__column" id="Contact">
					<h3>CONTACT</h3>
					<p>
						 Vous voulez parler à Lux? Prenez tout simplement contact avec nous.
					</p>
					<form action="" class="Form" id="formContato">
						<div class="Form__group" data-validate="true">
							<input name="contact_name" type="text" placeholder="NOM">
						</div>
						<div class="Form__group" data-validate="true">
							<input name="contact_email" type="email" placeholder="E-MAIL">
						</div>
						<div class="Form__group">
							<input name="contact_phone" type="tel" placeholder="Téléphone">
						</div>
						<div class="Form__group" data-validate="true">
							<textarea name="contact_message" id="" cols="5" rows="5" placeholder="MESSAGE"></textarea>
						</div>

						<button class="Button" type="submit">ENVOYEZ</button>
					</form>
				</div>
			</section> <!-- Contato -->

			<section class="Info">
				<div class="Info__item--right">
					<div class="Info__img" style="background-image: url(assets/img/contato2.jpg);"></div>
					<div class="Info__text">
						<h3>NEWSLETTER</h3>
						<p>
							Entrez votre email pour recevoir les dernières nouvelles.
						</p>
						<form action="" class="Form" id="formNews">
							<div class="Form__group" data-validate="true">
								<input name="news_nome" type="text" placeholder="NOM">
							</div>
							<div class="Form__group" data-validate="true">
								<input name="news_email" type="email" placeholder="E-MAIL">
							</div>

							<button class="Button" type="submit">ENVOYEZ</button>
						</form>
					</div>
				</div>

				<div class="Info__item">
					<div class="Info__img">
						<div id="map"></div>
					</div>
					<div class="Info__text">
						<h3>NOTRE LOCALISATION</h3>
						<ul class="ContactList">
							<li>
								<i class="icon icon-pin"></i> 64 Avenue de la Liberté,<br> L-1930 Luxembourg
							</li>
							<li>
								<i class="icon icon-tel"></i> Téléphone 1: (+352) 661 888 818<br>
								Téléphone 2: (+32) 485 650 175<br>
								Téléphone 3: (+33) 663 251 910<br>
							</li>
							<li>
								<i class="icon icon-email"></i> E-mail: info@luxsellect.com
							</li>
						</ul>
					</div>
				</div>
			</section>
			<!-- Info -->

		</div> <!-- PageContent -->

		<footer class="SiteFooter">
			<div class="container">
				<img src="assets/img/logo-negativo.png" alt="Lux Sell Ect" class="SiteFooter__logo">

				<div class="SiteFooter__social">
					<span>LUX SOCIAL</span>
					<ul>
						<li>
							<a href="https://www.facebook.com/LuxSellect-133974377117263/">
								<svg width="24px" height="49px" viewBox="0 0 24 49" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
									<!-- Generator: Sketch 47.1 (45422) - http://www.bohemiancoding.com/sketch -->
									<title>facebook</title>
									<defs></defs>
									<g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
										<g class="icon" fill-rule="nonzero" fill="#FFFFFF">
											<path d="M23.43,15.739 L15.785,15.739 L15.785,10.725 C15.785,8.842 17.033,8.403 17.912,8.403 C18.789,8.403 23.307,8.403 23.307,8.403 L23.307,0.125 L15.877,0.096 C7.629,0.096 5.752,6.27 5.752,10.221 L5.752,15.739 L0.982,15.739 L0.982,24.269 L5.752,24.269 C5.752,35.216 5.752,48.406 5.752,48.406 L15.785,48.406 C15.785,48.406 15.785,35.086 15.785,24.269 L22.555,24.269 L23.43,15.739 Z"
											 id="Shape"></path>
										</g>
									</g>
								</svg>
							</a>
						</li>
						<li>
							<a href="https://www.instagram.com/luxsellect/">
								<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 56.7 56.7" enable-background="new 0 0 56.7 56.7" xml:space="preserve"><g><path fill="#FFFFFF" d="M28.2,16.7c-7,0-12.8,5.7-12.8,12.8s5.7,12.8,12.8,12.8S41,36.5,41,29.5S35.2,16.7,28.2,16.7z M28.2,37.7 c-4.5,0-8.2-3.7-8.2-8.2s3.7-8.2,8.2-8.2s8.2,3.7,8.2,8.2S32.7,37.7,28.2,37.7z"/><circle fill="#FFFFFF" cx="41.5" cy="16.4" r="2.9"/><path fill="#FFFFFF" d="M49,8.9c-2.6-2.7-6.3-4.1-10.5-4.1H17.9c-8.7,0-14.5,5.8-14.5,14.5v20.5c0,4.3,1.4,8,4.2,10.7c2.7,2.6,6.3,3.9,10.4,3.9 h20.4c4.3,0,7.9-1.4,10.5-3.9c2.7-2.6,4.1-6.3,4.1-10.6V19.3C53,15.1,51.6,11.5,49,8.9z M48.6,39.9c0,3.1-1.1,5.6-2.9,7.3 s-4.3,2.6-7.3,2.6H18c-3,0-5.5-0.9-7.3-2.6C8.9,45.4,8,42.9,8,39.8V19.3c0-3,0.9-5.5,2.7-7.3c1.7-1.7,4.3-2.6,7.3-2.6h20.6 c3,0,5.5,0.9,7.3,2.7c1.7,1.8,2.7,4.3,2.7,7.2V39.9L48.6,39.9z"/></g></svg>
							</a>
						</li>
					</ul>
				</div>
			</div> <!-- container -->
			<a class="inffus" title="Powered by Inffus" href="https://inffus.com" target="_blank"><img src="https://inffus.com/inffus-web-intelligence.svg" width="25"></a>

		</footer> <!-- SiteFooter -->
	</div> <!-- PageWrapper -->