<div id="modalWrapper"></div>

<?php
	
	$veiculoModal = DAOFactory::getVeiculoDAO()->relTable('
	
														SELECT 
														*,v.alias as alias,
														v.idAlbum as idAlbum,
														c.nome as idCor,
														vc.alias as idVeiculoCategoria,
														m.nome as idMarca,
														m.idMarca as km,
														fuel.tipo as idCombustivel,
														trans.tipo as idTransmissao,
														sen.tipo as idSensor
														
														FROM Veiculo v 
														
														INNER JOIN Marca m ON (v.idMarca=m.idMarca)
														INNER JOIN Cor c ON (c.idCor=v.idCor)
														LEFT JOIN Combustivel fuel ON (v.idCombustivel=fuel.idCombustivel)
														LEFT JOIN Transmissao trans ON (v.idTransmissao=trans.idTransmissao)
														lEFT JOIN Sensor sen ON (v.idSensor=sen.idSensor)
														INNER JOIN veiculoCategoria vc ON (vc.idVeiculoCategoria=v.idVeiculoCategoria)


														WHERE v.status>0  ');
													
for($i=0;$i<count($veiculoModal);$i++){ 
	
	$rowVeiculo = $veiculoModal[$i]; 
	$albumModal = DAOFactory::getAlbumMidiaDAO()->queryCondList(' idAlbum="'.$rowVeiculo->idAlbum.'" ORDER BY ordem ASC '); 										


?>
<div class="modal fade lux-modal" tabindex="-1" role="dialog" id="carro<?=$rowVeiculo->idVeiculo?>">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			
			<img src="assets/img/logo.png" alt="Lux Sell Ect" class="lux-modal__logo">

			<button class="lux-modal__close js-close" data-dismiss="modal" aria-label="Close">
				<span></span>
			</button>

			<div class="lux-modal-content">
				<div class="lux-modal__column">
					<div class="lux-modal-slider js-slider-modal">
						<?php for($j=0;$j<count($albumModal);$j++){  ?>
						<div class="lux-modal-slider__item" style="background-image: url(/assets/img/albuns/album_<?=$albumModal[$j]->idAlbum?>/<?=$albumModal[$j]->file?>); "></div>
						<?php } ?>
					</div>
					<div class="lux-modal-slider-nav js-slider-modal-nav">
						<?php for($j=0;$j<count($albumModal);$j++){  ?>
						<div class="lux-modal-slider-nav__item" style="background-image: url(/assets/img/albuns/album_<?=$albumModal[$j]->idAlbum?>/<?=$albumModal[$j]->file?>); "></div>
						<?php } ?>
					</div>
					<footer class="lux-modal__footer">
						<span>COMPARTILHAR: </span>
						<ul>
							<li><a href="https://www.facebook.com/sharer/sharer.php?u=<?=$siteUrl?>" target="_blank"><img src="assets/img/icons/facebook2.svg" alt="Facebook"></a></li>
							<li><a href="https://twitter.com/home?status=<?=$rowVeiculo->modelo?>%20@%20LuxSellEct%0A<?=$siteUrl?>" target="_blank"><img src="assets/img/icons/twitter2.svg" alt="Twitter"></a></li>
							<li><a href="mailto:?subject=Lux Sell Ect / <?=$rowVeiculo->modelo?>&body=%0A%0A<?=$rowVeiculo->idMarca?> - <?=$rowVeiculo->modelo?>%0A%0A<?=$siteTitle?>%0A<?=$siteUrl?>%0A%0A" target="_blank"><img src="assets/img/icons/email.svg" alt="Email"></a></li>
						</ul>
					</footer>
				</div>
				<div class="lux-modal__column">
					<div class="lux-modal__desc">
						<div class="lux-modal__title">
							<h4>
								<small><?=$rowVeiculo->idMarca?></small> <?=$rowVeiculo->modelo?>
							</h4>
						</div>

						<p><?=$rowVeiculo->motor?></p>
						<p><?=$rowVeiculo->km?></p>

						<div class="Car-info">
							<div class="Car-info__date">
								<?=$rowVeiculo->anoModelo?>
							</div>

							<div class="Car-info__price">
								<?=$rowVeiculo->preco?>
							</div>
						</div>

						<div class="js-scrollbar">
						
						<ul>	
							<?php if($rowVeiculo->idMarca!=''){ ?><li>Marca: <span><?=$rowVeiculo->idMarca?></span></li><?php } ?>  
							<?php if($rowVeiculo->modelo!=''){ ?><li>Modelo: <span><?=$rowVeiculo->modelo?></span></li><?php } ?>  
							<?php if($rowVeiculo->preco!=''){ ?><li>Preço: <span>R$ <?=$rowVeiculo->preco?></span></li><?php } ?> 
							<?php if($rowVeiculo->idCor!=''){ ?><li>Cor: <span><?=$rowVeiculo->idCor?></span></li><?php } ?>
							<?php if($rowVeiculo->anoFabricacao!=''){ ?><li>Ano de fabricação: <span><?=$rowVeiculo->anoFabricacao?></span></li><?php } ?>
							<?php if($rowVeiculo->anoModelo!=''){ ?><li>Ano do modelo: <span><?=$rowVeiculo->anoModelo?></span></li><?php } ?>
							<?php if($rowVeiculo->km!=''){ ?><li>Km: <span><?=$rowVeiculo->km?></span></li><?php } ?>  		
							<?php if($rowVeiculo->motor!=''){ ?><li>Motor: <span><?=$rowVeiculo->motor?></span></li><?php } ?>
							<?php if($rowVeiculo->potencia!=''){ ?><li>Potência: <span><?=$rowVeiculo->potencia?></span></li><?php } ?>
							<?php if($rowVeiculo->aceleracao!=''){ ?><li>Aceleração: <span><?=$rowVeiculo->aceleracao?></span></li><?php } ?>
							<?php if($rowVeiculo->airbag!=''){ ?><li>Airbag: <span><?=$rowVeiculo->airbag?></span></li><?php } ?>
							<?php if($rowVeiculo->garantiaFabrica!=''){ ?><li>Garantia de fábrica: <span><?=$rowVeiculo->garantiaFabrica?></span></li><?php } ?>
							<?php if($rowVeiculo->idCombustivel!=''){ ?><li>Combustível: <span><?=$rowVeiculo->idCombustivel?></span></li><?php } ?>
							<?php if($rowVeiculo->idTransmissao!=''){ ?><li>Transmissão: <span><?=$rowVeiculo->idTransmissao?></span></li><?php } ?>
							<?php if($rowVeiculo->placa!=''){ ?><li>Placa: <span>XXX-<?=substr($rowVeiculo->placa, -4)?></span></li><?php } ?>
							<?php if($rowVeiculo->Portas!=''){ ?><li>Portas: <span><?=$rowVeiculo->portas?></span></li><?php } ?>
							<?php if($rowVeiculo->Motor!=''){ ?><li>Motor: <span><?=$rowVeiculo->motor?></span></li><?php } ?>
							<?php if($rowVeiculo->multimidia!=''){ ?><li>Multimídia: <span><?=$rowVeiculo->multimidia?></span></li><?php } ?>
							<?php if($rowVeiculo->bancos!=''){ ?><li>Bancos: <span><?=$rowVeiculo->bancos?></span></li><?php } ?>
							<?php if($rowVeiculo->freios!=''){ ?><li>Freios: <span><?=$rowVeiculo->freios?></span></li><?php } ?>
							<?php if($rowVeiculo->farois!=''){ ?><li>Faróis: <span><?=$rowVeiculo->farois?></span></li><?php } ?>
							<?php if($rowVeiculo->rodas!=''){ ?><li>Rodas: <span><?=$rowVeiculo->rodas?></span></li><?php } ?>
							<?php if($rowVeiculo->idSensor!=''){ ?><li>Sensor de estacionamento: <span><?=$rowVeiculo->idSensor?></span></li><?php } ?>
							<?php if($rowVeiculo->bluetooth=='sim'){ ?><li>Bluetooth: <span><?=strtoupper($rowVeiculo->bluetooth)?></span></li><?php } ?>
							<?php if($rowVeiculo->tetoSolar=='sim' or $rowVeiculo->tetoSolar=='semipanoramico'){ ?><li>Teto Solar: <span><?=strtoupper($rowVeiculo->tetoSolar)?></span></li><?php } ?>
							<?php if($rowVeiculo->conversivel=='sim'){ ?><li>Conversível: <span><?=strtoupper($rowVeiculo->conversivel)?></span></li><?php } ?>
							
							<?php if($rowVeiculo->pilotoAutomatico=='sim'){ ?><li>Piloto Automático: <span><?=strtoupper($rowVeiculo->pilotoAutomatico)?></span></li><?php } ?>
							
							<?php if($rowVeiculo->sensorChuva=='sim'){ ?><li>Sensor de Chuva: <span><?=strtoupper($rowVeiculo->sensorChuva)?></span></li><?php } ?>
							<?php if($rowVeiculo->blindado=='sim'){ ?><li>Blindado: <span><?=strtoupper($rowVeiculo->blindado)?></span></li><?php } ?>
							<?php if($rowVeiculo->observacoes!=''){ ?><li>Observações: <span><?=strtoupper($rowVeiculo->observacoes)?></span></li><?php } ?>

						</ul>	
							
							
						</div>

						<a href="#Contact" class="Button js-scroll" data-dismiss="modal" aria-label="Close">
							ENTRAR EM CONTATO
						</a>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
<?php } ?>

 
	<div class="PageWrapper">
		<header class="Header">
			<div class="container">
				<a href="index.html" class="Header__logo">
					<img src="assets/img/logo.png" alt="Lux Sell Ect">
				</a>

				<span></span>

				<a href="#/" class="MenuTrigger">
					<span></span>
				</a>

				<nav class="Menu">
					<div class="Menu__info">
						<img src="assets/img/logo-negativo.png" alt="Lux Sell Ect">
						<p>
							Olá, <br><br> Bem vindo a página da Lux Sell Ect Automóveis.<br>Encontre os melhores veículos aqui.
						</p>

						<ul class="Menu__redes">
							<li>
								<a href="/#" target="_blank">
									<img src="assets/img/icons/facebook.svg" alt="Facebook">
								</a>
							</li>
							<li>
								<a href="/#" target="_blank">
									<img src="assets/img/icons/twitter.svg" alt="Twitter">
								</a>
							</li>
						</ul>
					</div> <!-- Menu__info -->

					<ul class="Menu__nav">
						<li><a href="#LuxSellEct" class="js-scroll">EMPRESA</a></li>
						<li><a href="#Releases" class="js-scroll">CARROS</a></li>
						<li><a href="#index.html" class="Menu__navLogo"><img src="assets/img/logo.png" alt="Lux Sell Ect"></a></li>
						<li><a href="blog.html" target="_blank">BLOG</a></li>
						<li><a href="#Contact" class="js-scroll">CONTATO</a></li>
					</ul>
				</nav> <!-- Menu -->

			</div> <!-- container -->
		</header> <!-- Header -->

		<div class="PageContent">

			<section class="Banner js-bannerSlider">
				
				<?php 	
						$albumBannerHome = DAOFactory::getAlbumMidiaDAO()->queryCondList(' idAlbum="1" ');
						for($b=0;$b<count($albumBannerHome);$b++){ 
				  ?>
				
				<div class="Banner__item" style="background-image: url(/assets/img/albuns/album_<?=$albumBannerHome[$b]->idAlbum?>/<?=$albumBannerHome[$b]->file?>);">
					<div class="container">
						<div class="Banner__content">
							<h2><span><?=$albumBannerHome[$b]->nome?></span><?=$albumBannerHome[$b]->alt?></h2>
						</div> <!-- Banner-content -->
						<a href="#Releases" class="Banner__link js-scroll">new releases</a>
					</div> <!-- container -->
				</div>  <!-- Banner__item -->
				
				<?php } ?>
				
			</section> <!-- Banner -->

			<section id="Releases" class="Release">
				<div class="Release__title">
					<div class="container">
						<h3>NEW RELEASES</h3>
					</div>
				</div>

				<div id="Cars" class="Grid js-grid">

					<!--<div class="Grid__item mix" data-marca="lamborghini" data-modelo="2013" data-valor="1000000">
						<div class="Grid__img" style="background-image: url(assets/img/carros/c1.jpg);"></div>
						
						<div class="Grid__content">
							<h4>
								<small>PORSCHE</small> PORSCHE 913
							</h4>

							<div class="Car-info">
								<div class="Car-info__date">
									2013
								</div>

								<div class="Car-info__price">
									700.000
								</div>
							</div>

						</div>
					</div>-->

			</div> <!-- js-grid -->

			<div class="Grid__load">
				<div class="container"></div>
			</div>


			</section> <!-- Release -->

			<section id="LuxSellEct" class="Info--border">
				<div class="Info__item">
					<div class="Info__img" style="background-image: url(assets/img/sobre.jpg);"></div>
					<div class="Info__text">
						<h3>EMPRESA</h3>
						<p>
							Lux Sell Ect is the luxury marketplace to find new and preowned luxury, exotic and classic cars for sale. Search more than
							2,000 luxury cars, exotic cars, classic cars and other supercars with large, high quality images.
						</p>
						<p>
							Founded in 2008, Lux Sell Ect today features the largest collection of luxury goods worldwide. Our 80,000 bespoke items curated
							by Lux Sell Ect range from rare supercars to celebrity owned luxury real estates. An affluent audience of 25,000 per
							day is browsing for the finest watches, helicopters and jets for sale.
						</p>
					</div>
				</div>

				<div class="Info__item--right">
					<div class="Info__img" style="background-image: url(assets/img/sobre2.jpg);"></div>
					<div class="Info__text">
						<h3>SERVIÇO<br>PERSONALIZADO</h3>
						<p>
							Founded in 2008, Lux Sell Ect today features the largest collection of luxury goods worldwide. Our 80,000 bespoke items curated
							by Lux Sell Ect range from rare supercars to celebrity owned luxury real estates. An affluent audience of 25,000 per
							day is browsing for the finest watches, helicopters and jets for sale.
						</p>
					</div>
				</div>
			</section> <!-- Info -->

			<section class="Instagram">
				<h3>
					SIGA A Lux Sell Ect <br>NO INSTAGRAM
				</h3>

				<div class="container">

					<img src="assets/img/iphone.jpg" alt="Iphone" class="Instagram__iphone">

					<div class="Instagram__box">
						<img src="assets/img/logo-negativo.png" alt="Lux Sell Ect">
						<img src="assets/img/instagram.jpg" alt="Instagram">
						<div id="instafeed" class="Instafeed"></div>

					</div>
				</div>
			</section> <!-- Instagram -->

			<section class="Contato">
				<div class="Contato__column" style="background-image: url(assets/img/contato.jpg); "></div>
				<div class="Contato__column" id="Contact">
					<h3>CONTATO</h3>
					<p>
						 Quer falar com a Lux? Entre em contato abaixo e retornaremos brevemente!
					</p>
					<form action="" class="Form" id="formContato">
						<div class="Form__group" data-validate="true">
							<input name="contact_name" type="text" placeholder="NAME">
						</div>
						<div class="Form__group" data-validate="true">
							<input name="contact_email" type="email" placeholder="E-MAIL">
						</div>
						<div class="Form__group">
							<input name="contact_phone" type="tel" placeholder="PHONE">
						</div>
						<div class="Form__group" data-validate="true">
							<textarea name="contact_message" id="" cols="5" rows="5" placeholder="MESSAGE"></textarea>
						</div>

						<button class="Button" type="submit">enviar</button>
					</form>
				</div>
			</section> <!-- Contato -->

			<section class="Info">
				<div class="Info__item--right">
					<div class="Info__img" style="background-image: url(assets/img/contato2.jpg);"></div>
					<div class="Info__text">
						<h3>NEWSLETTER</h3>
						<p>
							 Cadastre seu nome e e-mail para receber as últimas novidades e lançamentos da Lux Sell Ect:
						</p>
						<form action="" class="Form" id="formNews">
							<div class="Form__group" data-validate="true">
								<input name="news_nome" type="text" placeholder="NOME">
							</div>
							<div class="Form__group" data-validate="true">
								<input name="news_email" type="email" placeholder="E-MAIL">
							</div>

							<button class="Button" type="submit">enviar</button>
						</form>
					</div>
				</div>

				<div class="Info__item">
					<div class="Info__img">
						<div id="map"></div>
					</div>
					<div class="Info__text">
						<h3>ONDE ESTAMOS</h3>
						<ul class="ContactList">
							<li>
								Alguma Rua, 987<br>Luxemburgo<br>12345
							</li>
							<li>
								+98 765 43 21
							</li>
						</ul>
					</div>
				</div>
			</section>
			<!-- Info -->

		</div> <!-- PageContent -->

		<footer class="SiteFooter">
			<div class="container">
				<img src="assets/img/logo-negativo.png" alt="Lux Sell Ect" class="SiteFooter__logo">

				<div class="SiteFooter__social">
					<span>LUX SOCIAL</span>
					<ul>
						<li>
							<a href="#">
								<svg width="24px" height="49px" viewBox="0 0 24 49" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
									<!-- Generator: Sketch 47.1 (45422) - http://www.bohemiancoding.com/sketch -->
									<title>facebook</title>
									<defs></defs>
									<g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
										<g class="icon" fill-rule="nonzero" fill="#FFFFFF">
											<path d="M23.43,15.739 L15.785,15.739 L15.785,10.725 C15.785,8.842 17.033,8.403 17.912,8.403 C18.789,8.403 23.307,8.403 23.307,8.403 L23.307,0.125 L15.877,0.096 C7.629,0.096 5.752,6.27 5.752,10.221 L5.752,15.739 L0.982,15.739 L0.982,24.269 L5.752,24.269 C5.752,35.216 5.752,48.406 5.752,48.406 L15.785,48.406 C15.785,48.406 15.785,35.086 15.785,24.269 L22.555,24.269 L23.43,15.739 Z"
											 id="Shape"></path>
										</g>
									</g>
								</svg>
							</a>
						</li>
						<li>
							<a href="#">
								<svg width="50px" height="41px" viewBox="0 0 50 41" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
									<!-- Generator: Sketch 47.1 (45422) - http://www.bohemiancoding.com/sketch -->
									<title>twitter</title>
									<defs></defs>
									<g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
										<g class="icon" fill-rule="nonzero" fill="#FFFFFF">
											<path d="M49.837,5.065 C48.026,5.87 46.077,6.413 44.032,6.656 C46.12,5.406 47.721,3.426 48.476,1.064 C46.523,2.223 44.361,3.064 42.058,3.518 C40.215,1.554 37.588,0.326 34.681,0.326 C29.1,0.326 24.575,4.851 24.575,10.433 C24.575,11.224 24.664,11.995 24.837,12.736 C16.437,12.314 8.989,8.291 4.004,2.176 C3.134,3.668 2.636,5.404 2.636,7.258 C2.636,10.764 4.42,13.858 7.132,15.67 C5.476,15.617 3.917,15.162 2.554,14.405 C2.553,14.447 2.553,14.49 2.553,14.533 C2.553,19.429 6.037,23.513 10.661,24.443 C9.813,24.673 8.92,24.797 7.998,24.797 C7.346,24.797 6.713,24.734 6.096,24.615 C7.383,28.63 11.115,31.553 15.537,31.634 C12.078,34.345 7.721,35.961 2.985,35.961 C2.17,35.961 1.365,35.913 0.574,35.819 C5.048,38.688 10.36,40.36 16.067,40.36 C34.658,40.36 44.823,24.96 44.823,11.604 C44.823,11.166 44.814,10.729 44.795,10.295 C46.769,8.873 48.483,7.092 49.837,5.065 Z"
											 id="Shape"></path>
										</g>
									</g>
								</svg>
							</a>
						</li>
					</ul>
				</div>				
			</div> <!-- container -->

		</footer> <!-- SiteFooter -->
	</div> <!-- PageWrapper -->